scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.2625
        max_y: 0.2696
        max_z: 0.5
        min_x: -0.2125
        min_y: -0.2696
        min_z: 0.0
        
        invert: false # activate to remove all points outside of the box
